// <auto-generated />
using System;
using ExcelToSqlProgram.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcelToSqlProgram.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230518085310_ExcelData")]
    partial class ExcelData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExcelToSqlProgram.Models.ExcelData", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<float?>("COGS")
                        .HasColumnType("real");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discount_Band")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Discounts")
                        .HasColumnType("real");

                    b.Property<float?>("Gross_Sales")
                        .HasColumnType("real");

                    b.Property<float?>("Manufacturing_Price")
                        .HasColumnType("real");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Profit")
                        .HasColumnType("real");

                    b.Property<float?>("Sale_Price")
                        .HasColumnType("real");

                    b.Property<float?>("Sales")
                        .HasColumnType("real");

                    b.Property<string>("Segment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Units_Sold")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ExcelData");
                });
#pragma warning restore 612, 618
        }
    }
}
